In [20]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import math
from sklearn.cross_validation import KFold
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.model_selection import RandomizedSearchCV,train_test_split,GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from xgboost.sklearn import XGBClassifier

In [3]:
datafile_train=r'C:\Users\sujith\Desktop\Project\p2\carvan_train.csv'
datafile_test=r'C:\Users\sujith\Desktop\Project\p2\carvan_test.csv'
ca_train=pd.read_csv(datafile_train)
ca_test=pd.read_csv(datafile_test)

In [5]:
ca_train.dtypes

V1     int64
V2     int64
V3     int64
V4     int64
V5     int64
V6     int64
V7     int64
V8     int64
V9     int64
V10    int64
V11    int64
V12    int64
V13    int64
V14    int64
V15    int64
V16    int64
V17    int64
V18    int64
V19    int64
V20    int64
V21    int64
V22    int64
V23    int64
V24    int64
V25    int64
V26    int64
V27    int64
V28    int64
V29    int64
V30    int64
       ...  
V57    int64
V58    int64
V59    int64
V60    int64
V61    int64
V62    int64
V63    int64
V64    int64
V65    int64
V66    int64
V67    int64
V68    int64
V69    int64
V70    int64
V71    int64
V72    int64
V73    int64
V74    int64
V75    int64
V76    int64
V77    int64
V78    int64
V79    int64
V80    int64
V81    int64
V82    int64
V83    int64
V84    int64
V85    int64
V86    int64
Length: 86, dtype: object

In [9]:
for col in ca_train.select_dtypes(['int64']).columns:
    print(col,':',ca_train[col].nunique())

V1 : 40
V2 : 9
V3 : 5
V4 : 6
V5 : 10
V6 : 10
V7 : 10
V8 : 6
V9 : 10
V10 : 10
V11 : 8
V12 : 10
V13 : 10
V14 : 10
V15 : 10
V16 : 10
V17 : 10
V18 : 10
V19 : 10
V20 : 6
V21 : 10
V22 : 10
V23 : 10
V24 : 10
V25 : 10
V26 : 10
V27 : 10
V28 : 10
V29 : 9
V30 : 10
V31 : 10
V32 : 10
V33 : 8
V34 : 10
V35 : 10
V36 : 10
V37 : 10
V38 : 10
V39 : 10
V40 : 10
V41 : 8
V42 : 10
V43 : 8
V44 : 4
V45 : 7
V46 : 4
V47 : 6
V48 : 4
V49 : 6
V50 : 4
V51 : 6
V52 : 5
V53 : 5
V54 : 6
V55 : 10
V56 : 7
V57 : 3
V58 : 5
V59 : 9
V60 : 3
V61 : 7
V62 : 2
V63 : 7
V64 : 5
V65 : 3
V66 : 3
V67 : 2
V68 : 7
V69 : 5
V70 : 4
V71 : 4
V72 : 4
V73 : 5
V74 : 5
V75 : 3
V76 : 6
V77 : 2
V78 : 2
V79 : 3
V80 : 7
V81 : 2
V82 : 3
V83 : 4
V84 : 3
V85 : 3
V86 : 2


In [11]:
ca_train.shape

(5822, 86)

In [16]:
ca1_train,ca1_test=train_test_split(ca_train,test_size=0.2,random_state=2)

In [18]:
ca1_train.reset_index(drop=True,inplace=True)
ca1_test.reset_index(drop=True,inplace=True)

In [19]:
x_train=ca1_train.drop('V86',axis=1)
x_test=ca1_test.drop('V86',axis=1)

y_train=ca1_train['V86']
y_test=ca1_test['V86']

In [30]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score


In [76]:
logr=LogisticRegression(penalty="l1",class_weight="balanced",random_state=2)

In [77]:
logr.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l1', random_state=2,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [78]:

roc_auc_score(y_test,logr.predict(x_test))

0.6759633027522937

In [80]:
r=logr.predict(ca_test)

In [81]:
r

array([0, 1, 0, ..., 1, 0, 1], dtype=int64)

In [84]:
submission=pd.DataFrame(list(r),
                       columns=['V86'])

In [86]:
submission['V86'].value_counts()

0    2775
1    1225
Name: V86, dtype: int64

In [87]:
submission.to_csv('submission.csv',index=False)

In [97]:
q=logr.predict_proba(x_test)

In [98]:
q=np.where(q[:,0]>=0.33,0,1)

In [99]:

roc_auc_score(y_test,q)

0.6574006116207951

In [79]:
prob_score=pd.Series(list(zip(*logr.predict_proba(x_train)))[1])

In [88]:
prob_score

0       0.391726
1       0.055335
2       0.444702
3       0.187836
4       0.297118
5       0.337893
6       0.493738
7       0.642845
8       0.333005
9       0.164376
10      0.280343
11      0.207722
12      0.311112
13      0.129132
14      0.805337
15      0.160109
16      0.207534
17      0.379601
18      0.172736
19      0.029429
20      0.056204
21      0.095381
22      0.141770
23      0.167320
24      0.857397
25      0.733932
26      0.203039
27      0.429215
28      0.103768
29      0.834458
          ...   
4627    0.020891
4628    0.260555
4629    0.523832
4630    0.582448
4631    0.020891
4632    0.857498
4633    0.443521
4634    0.069925
4635    0.766859
4636    0.284156
4637    0.207651
4638    0.172771
4639    0.737521
4640    0.675861
4641    0.196181
4642    0.126862
4643    0.846219
4644    0.032253
4645    0.319109
4646    0.116383
4647    0.725381
4648    0.129695
4649    0.125335
4650    0.315990
4651    0.338352
4652    0.060818
4653    0.643363
4654    0.5502

In [51]:
cutoffs=np.linspace(0,1,100)

In [52]:
KS_cut=[]
for cutoff in cutoffs:
    predicted=pd.Series([0]*len(y_train))
    predicted[prob_score>cutoff]=1
    df=pd.DataFrame(list(zip(y_train,predicted)),columns=["real","predicted"])
    TP=len(df[(df["real"]==1) &(df["predicted"]==1) ])
    FP=len(df[(df["real"]==0) &(df["predicted"]==1) ])
    TN=len(df[(df["real"]==0) &(df["predicted"]==0) ])
    FN=len(df[(df["real"]==1) &(df["predicted"]==0) ])
    P=TP+FN
    N=TN+FP
    KS=(TP/P)-(FP/N)
    KS_cut.append(KS)

cutoff_data=pd.DataFrame(list(zip(cutoffs,KS_cut)),columns=["cutoff","KS"])

KS_cutoff=cutoff_data[cutoff_data["KS"]==cutoff_data["KS"].max()]["cutoff"]

In [53]:
prob_score_test=pd.Series(list(zip(*logr.predict_proba(x_test)))[1])

predicted_test=pd.Series([0]*len(y_test))
predicted_test[prob_score_test>float(KS_cutoff)]=1

df_test=pd.DataFrame(list(zip(y_test,predicted_test)),columns=["real","predicted"])

k=pd.crosstab(df_test['real'],df_test["predicted"])
print('confusion matrix :\n \n ',k)
TN=k.iloc[0,0]
TP=k.iloc[1,1]
FP=k.iloc[0,1]
FN=k.iloc[1,0]
P=TP+FN
N=TN+FP

confusion matrix :
 
  predicted    0    1
real               
0          848  242
1           36   39


In [54]:
(TP+TN)/(P+N)

0.76137339055794

In [55]:
TP/P

0.52

In [56]:
TN/N

0.7779816513761468

In [74]:
cutoffs=np.linspace(0.010,0.99,100)
def Fbeta_perf(beta,cutoffs,y_train,prob_score):
    FB_cut=[]
    for cutoff in cutoffs:
        predicted=pd.Series([0]*len(y_train))
        predicted[prob_score>cutoff]=1
        df=pd.DataFrame(list(zip(y_train,predicted)),columns=["real","predicted"])

        TP=len(df[(df["real"]==1) &(df["predicted"]==1) ])
        FP=len(df[(df["real"]==0) &(df["predicted"]==1) ])
        FN=len(df[(df["real"]==1) &(df["predicted"]==0) ])
        P=TP+FN
        
        
        Precision=TP/(TP+FP)
        Recall=TP/P
        FB=(1+beta**2)*Precision*Recall/((beta**2)*Precision+Recall)
        FB_cut.append(FB)

    cutoff_data=pd.DataFrame(list(zip(cutoffs,FB_cut)),columns=["cutoff","FB"])

    FB_cutoff=cutoff_data[cutoff_data["FB"]==cutoff_data["FB"].max()]["cutoff"]

    prob_score_test=pd.Series(list(zip(*logr.predict_proba(x_test)))[1])

    predicted_test=pd.Series([0]*len(y_test))
    predicted_test[prob_score_test>float(FB_cutoff)]=1

    df_test=pd.DataFrame(list(zip(y_test,predicted_test)),columns=["real","predicted"])

    k=pd.crosstab(df_test['real'],df_test["predicted"])
#     print('confusion matrix :\n \n ',k)
    TN=k.iloc[0,0]
    TP=k.iloc[1,1]
    FP=k.iloc[0,1]
    FN=k.iloc[1,0]
    P=TP+FN
    N=TN+FP
    print('For beta :',beta)
    print('Accuracy is :',(TP+TN)/(P+N))
    print('Sensitivity is :',(TP/P))
    print('Specificity is :',(TN/N))
    Precision=TP/(TP+FP)
        
    Recall=TP/P
    print(cutoff)    
    print('F Beta is = ',(1+beta**2)*Precision*Recall/((beta**2)*Precision+Recall))
    print('\n \n \n')

In [75]:
Fbeta_perf(0.5,cutoffs,y_train,prob_score)
Fbeta_perf(1,cutoffs,y_train,prob_score)
Fbeta_perf(2,cutoffs,y_train,prob_score)

For beta : 0.5
Accuracy is : 0.9158798283261803
Sensitivity is : 0.22666666666666666
Specificity is : 0.963302752293578
0.99
F Beta is =  0.28052805280528054

 
 

For beta : 1
Accuracy is : 0.8583690987124464
Sensitivity is : 0.37333333333333335
Specificity is : 0.8917431192660551
0.99
F Beta is =  0.253393665158371

 
 

For beta : 2
Accuracy is : 0.7587982832618025
Sensitivity is : 0.52
Specificity is : 0.7752293577981652
0.99
F Beta is =  0.3339041095890411

 
 



In [59]:
xgb_params = {  
                "learning_rate":[0.01,0.05,0.1,0.3,0.5],
                "gamma":[i/10.0 for i in range(0,5)],
                "max_depth": [2,3,4,5,6,7,8],
                "min_child_weight":[1,2,5,10],
                "max_delta_step":[0,1,2,5,10],
                "subsample":[i/10.0 for i in range(5,10)],
                "colsample_bytree":[i/10.0 for i in range(5,10)],
                "colsample_bylevel":[i/10.0 for i in range(5,10)],
                "reg_lambda":[1e-5, 1e-2, 0.1, 1, 100], 
                "reg_alpha":[1e-5, 1e-2, 0.1, 1, 100],
                "scale_pos_weight":[1,2,3,4,5,6,7,8,9],
                "n_estimators":[100,500,700,1000]
             }


In [60]:
xgb=XGBClassifier(objective='binary:logistic')

In [61]:
n_iter=10

random_search=RandomizedSearchCV(xgb,n_jobs=-1,cv=5,n_iter=n_iter,scoring='roc_auc',
                                 param_distributions=xgb_params)

In [62]:
random_search.fit(x_train,y_train)

RandomizedSearchCV(cv=5, error_score='raise',
          estimator=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='binary:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1),
          fit_params=None, iid=True, n_iter=10, n_jobs=-1,
          param_distributions={'learning_rate': [0.01, 0.05, 0.1, 0.3, 0.5], 'gamma': [0.0, 0.1, 0.2, 0.3, 0.4], 'max_depth': [2, 3, 4, 5, 6, 7, 8], 'min_child_weight': [1, 2, 5, 10], 'max_delta_step': [0, 1, 2, 5, 10], 'subsample': [0.5, 0.6, 0.7, 0.8, 0.9], 'colsample_bytree': [0.5, 0.6, 0.7, 0.8, 0.9], 'co....1, 1, 100], 'scale_pos_weight': [1, 2, 3, 4, 5, 6, 7, 8, 9], 'n_estimators': [100, 500, 700, 1000]},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
     

In [63]:
def report(results, n_top=3):
    for i in range(1, n_top + 1):
        candidates = np.flatnonzero(results['rank_test_score'] == i)
        for candidate in candidates:
            print("Model with rank: {0}".format(i))
            print("Mean validation score: {0:.3f} (std: {1:.5f})".format(
                  results['mean_test_score'][candidate],
                  results['std_test_score'][candidate]))
            print("Parameters: {0}".format(results['params'][candidate]))
            print("")

In [64]:
report(random_search.cv_results_,5)

Model with rank: 1
Mean validation score: 0.763 (std: 0.02067)
Parameters: {'subsample': 0.8, 'scale_pos_weight': 6, 'reg_lambda': 100, 'reg_alpha': 100, 'n_estimators': 700, 'min_child_weight': 5, 'max_depth': 8, 'max_delta_step': 0, 'learning_rate': 0.1, 'gamma': 0.4, 'colsample_bytree': 0.7, 'colsample_bylevel': 0.8}

Model with rank: 2
Mean validation score: 0.761 (std: 0.01860)
Parameters: {'subsample': 0.6, 'scale_pos_weight': 9, 'reg_lambda': 100, 'reg_alpha': 1, 'n_estimators': 700, 'min_child_weight': 10, 'max_depth': 2, 'max_delta_step': 1, 'learning_rate': 0.01, 'gamma': 0.4, 'colsample_bytree': 0.8, 'colsample_bylevel': 0.5}

Model with rank: 3
Mean validation score: 0.760 (std: 0.01668)
Parameters: {'subsample': 0.7, 'scale_pos_weight': 9, 'reg_lambda': 0.1, 'reg_alpha': 100, 'n_estimators': 1000, 'min_child_weight': 10, 'max_depth': 8, 'max_delta_step': 5, 'learning_rate': 0.5, 'gamma': 0.2, 'colsample_bytree': 0.8, 'colsample_bylevel': 0.6}

Model with rank: 4
Mean valid

In [65]:
random_search.best_estimator_

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=0.8,
       colsample_bytree=0.7, gamma=0.4, learning_rate=0.1,
       max_delta_step=0, max_depth=8, min_child_weight=5, missing=None,
       n_estimators=700, n_jobs=1, nthread=None,
       objective='binary:logistic', random_state=0, reg_alpha=100,
       reg_lambda=100, scale_pos_weight=6, seed=None, silent=True,
       subsample=0.8)

In [66]:
xgb=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=0.8,
       colsample_bytree=0.7, gamma=0.4, learning_rate=0.1,
       max_delta_step=0, max_depth=8, min_child_weight=5, missing=None,
       n_estimators=700, n_jobs=1, nthread=None,
       objective='binary:logistic', random_state=0, reg_alpha=100,
       reg_lambda=100, scale_pos_weight=6, seed=None, silent=True,
       subsample=0.8)

In [67]:
n_iter=10

random_search=RandomizedSearchCV(xgb,n_jobs=-1,cv=5,n_iter=n_iter,scoring='roc_auc',
                                 param_distributions=xgb_params)

In [68]:
random_search.fit(x_train,y_train)

RandomizedSearchCV(cv=5, error_score='raise',
          estimator=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=0.8,
       colsample_bytree=0.7, gamma=0.4, learning_rate=0.1,
       max_delta_step=0, max_depth=8, min_child_weight=5, missing=None,
       n_estimators=700, n_jobs=1, nthread=None,
       objective='binary:logistic', random_state=0, reg_alpha=100,
       reg_lambda=100, scale_pos_weight=6, seed=None, silent=True,
       subsample=0.8),
          fit_params=None, iid=True, n_iter=10, n_jobs=-1,
          param_distributions={'learning_rate': [0.01, 0.05, 0.1, 0.3, 0.5], 'gamma': [0.0, 0.1, 0.2, 0.3, 0.4], 'max_depth': [2, 3, 4, 5, 6, 7, 8], 'min_child_weight': [1, 2, 5, 10], 'max_delta_step': [0, 1, 2, 5, 10], 'subsample': [0.5, 0.6, 0.7, 0.8, 0.9], 'colsample_bytree': [0.5, 0.6, 0.7, 0.8, 0.9], 'co....1, 1, 100], 'scale_pos_weight': [1, 2, 3, 4, 5, 6, 7, 8, 9], 'n_estimators': [100, 500, 700, 1000]},
          pre_dispatch='2*n_jobs', random_state=None

In [70]:
l=random_search.predict_proba(x_test)

In [71]:
l

array([[0.5431392 , 0.45686078],
       [0.7242397 , 0.27576026],
       [0.43199867, 0.56800133],
       ...,
       [0.44087374, 0.55912626],
       [0.8324307 , 0.16756931],
       [0.78163016, 0.21836981]], dtype=float32)

In [72]:
l=np.where(l[:,0]>=0.5,0,1)

In [69]:
random_search.classes_

array([0, 1], dtype=int64)

In [73]:

roc_auc_score(y_test,l)

0.6364220183486238